// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database
}

declare global {
  interface Window {
    // __SITE__: Site
    __SITE__: any
    __USER_ID__: string
  }
}
